---
grails:
    profile: web
    codegen:
        defaultPackage: facturation
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
management:
    endpoints:
        enabled-by-default: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlet: html
                taglib: none
                staticparts: none
    databinding:
        dateFormats:
            - yyyy-MM-dd
            - yyyy-MM-dd HH:mm:ss.S
            - yyyy-MM-dd’T’hh:mm:ss’Z'
            - yyyy-MM-dd HH:mm:ss.S z
            - yyyy-MM-dd’T’HH:mm:ss.SSSX
management:
    endpoints:
        jmx:
            unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false

---
app:
    pagination:
        max: 25
        
        
---
# en doublon de application.groovy mais celui-ci n'est pas chargé
# depuis le lancement de init/Application.groovy (spring boot)
#grails:
#    plugin:
#        springsecurity:
#            password:
#                algorithm: bcrypt
#            userLookup:
#                userDomainClassName: facturation.User
#                authorityJoinClassName: facturation.UserRole
#            authority:
#                className: facturation.Role
#            controllerAnnotations:
#                staticRules:
#                  - {pattern: /error, access: [permitAll]}
#                  - {pattern: /shutdown, access: [permitAll]}
#                  - {pattern: /assets/**, access: [permitAll]}
#                  - {pattern: /**/js/**, access: [permitAll]}
#                  - {pattern: /**/css/**, access: [permitAll]}
#                  - {pattern: /**/images/**, access: [permitAll]}
#                  - {pattern: /**/favicon.ico, access: [permitAll]}
#            filterChain:
#                chainMap:
#                  - {pattern: /assets/**, filters: none}
#                  - {pattern: /**/js/**, filters: none}
#                  - {pattern: /**/css/**, filters: none}
#                  - {pattern: /**/images/**, filters: none}
#                  - {pattern: /**/favicon.ico, filters: none}
#                  - {pattern: /**, filters: JOINED_FILTERS}

